core/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('core.views',
    (r'^customer/$', 'customer_home'),
    (r'^customer/view/(?P<id>.*)/$', 'customer_view'),
    (r'^customer/add/$', 'add_customer'),
    (r'^customer/edit/(?P<id>.*)/$', 'edit_customer'),
    (r'^customer/delete/(?P<id>.*)/$', 'delete_customer'),

    (r'^category/$', 'category_home'),
    (r'^category/view/(?P<id>.*)/$', 'category_view'),
    (r'^category/add/$', 'add_category'),
    (r'^category/edit/(?P<id>.*)/$', 'edit_category'),

    (r'^product/$', 'product_home'),
    (r'^product/view/(?P<id>.*)/$', 'product_view'),
    (r'^product/add/$', 'add_product'),
    (r'^product/edit/(?P<id>.*)/$', 'edit_product'),
    (r'^product/delete/(?P<id>.*)/$', 'delete_product'),

    (r'^sale/$', 'sale_home'),
    (r'^sale/view/(?P<id>.*)/$', 'sale_view'),
    (r'^sale/add/$', 'add_sale'),
    (r'^sale/random/$', 'add_random_sales'),
    (r'^sale/edit/(?P<id>.*)/$', 'edit_sale'),
    (r'^sale/delete/(?P<id>.*)/$', 'delete_sale'),

    (r'^campaign/$', 'campaign_home'),
    (r'^campaign/view/(?P<id>.*)/$', 'campaign_view'),
    (r'^campaign/add/$', 'add_campaign'),
    (r'^campaign/edit/(?P<id>.*)/$', 'edit_campaign'),
    (r'^campaign/delete/(?P<id>.*)/$', 'delete_campaign'),

    (r'^group/$', 'group_home'),
    (r'^group/view/(?P<id>.*)/$', 'group_view'),
    (r'^csv/', include('csvimporter.urls')),

)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to
from django.views.generic.simple import direct_to_template
from home.views import tlogin

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()
urlpatterns = patterns('',
    (r'^static/(?P<path>.*)/$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    (r'^admin/', include(admin.site.urls)),
    (r'^home/', include('home.urls')),
    (r'^$', redirect_to, {'url': '/home/'}),
    (r'^core/', include('core.urls')),
    (r'^landing/', direct_to_template, {'template': settings.MEDIA_ROOT + '/landing/index.html'}),
    (r'^index-2/', direct_to_template, {'template': settings.MEDIA_ROOT + '/landing/index-2.html'}),
    (r'^about/', direct_to_template, {'template': settings.MEDIA_ROOT + '/landing/about.html'}),
    (r'^pricing/', direct_to_template, {'template': settings.MEDIA_ROOT + '/landing/pricing.html'}),
    (r'^blog/', direct_to_template, {'template': settings.MEDIA_ROOT + '/landing/blog.html'}),
    (r'^contact/', direct_to_template, {'template': settings.MEDIA_ROOT + '/landing/contact.html'}),

    (r'^login/$', tlogin),
    #(r'^login/$', login),
    (r'^logout/$', 'django.contrib.auth.views.logout'),
    (r'^forgot_password/$', 'home.views.forgot_password'),
    (r'^signup/$', 'home.views.signup'),
    (r'^signup_success/$', 'home.views.signup_success'),
    url(r'^groups/(?P<name>.+)/$', 'groups.views.detail', {}, name='group_detail'),

)

core/models.py
from datetime import datetime
from django.db import models
from django.db.models import Sum, Count
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))

class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User)

    # Other fields here
    paid_user = models.BooleanField()
User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u,paid_user=True)[0])

class Group():
    """
    represents a virtual group
    note: no respctive database table
    """


    def __init__(self, user):
        self.user = user
        self.GROUP_DEFINITIONS = ({'id': 0, 'name': 'Prospective Buyers'}, {'id': 1, 'name': 'First Time Buyers'},
                                      {'id': 2, 'name': 'Repeat Buyers'})

    def get_group(self, id):
        id = int(id)
        if id < 2:
            customers = Customer.objects.filter(user=self.user).annotate(bought=Count('sale')).filter(bought=id)
        else:
            customers = Customer.objects.filter(user=self.user).annotate(bought=Count('sale')).filter(bought__gte=id)
        self.GROUP_DEFINITIONS[id]['customers'] = customers
        self.GROUP_DEFINITIONS[id]['total_turnover'] = sum(
            [customer.total_turnover_generated() for customer in customers])
        return self.GROUP_DEFINITIONS[id]

    def get_group_customers_query(self, id):
        id = int(id)
        if id < 2:
            return Customer.objects.filter(user=self.user).annotate(bought=Count('sale')).filter(bought=id)
        else:
            return Customer.objects.filter(user=self.user).annotate(bought=Count('sale')).filter(bought__gte=id)


class Category(models.Model):
    """
    represents a group
    """
    CONNECTION_CHOICES = (
        (0, 'High'),
        (1, 'Medium'),
        (2, 'Low'),
        )

    name = models.CharField(_('name'), max_length=50, blank=False, null=False)
    characteristics = models.CharField(_('characteristics'), max_length=200, blank=True, null=True)
    interests = models.CharField(_('core interests'), max_length=200, blank=True, null=True)
    connection = models.SmallIntegerField(_('connection'), choices=CONNECTION_CHOICES, default=2)

    # foreign key mappings goes here
    user = models.ForeignKey(User, blank=False, null=False)

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

    def total_revenue_generated(self):
        """
        calculates total turnover generated by this category.
        boils down to sum of turnover generated by all customers in this category
        """
        turnover = Sale.objects.filter(customer__category=self).aggregate(turnover=Sum('price'))
        return turnover['turnover'] or 0.0


    def total_sales(self):
        return Sale.objects.filter(customer__category=self).count()

    def most_common_path(self):
        most_bought_products = Product.objects.filter(sale__customer__category=self).annotate(
            bought=Count('sale__product')).order_by('-bought')
        return ' > '.join(product.name for product in most_bought_products)

    def get_rank(self):
        groups_by_revenue = Category.objects.filter(user=self.user).annotate(
            revenue=Sum('customer__sale__price')).order_by('-revenue')
        counter = 0
        rank = len(categories_by_revenue)
        for each in categories_by_revenue:
            counter = counter + 1
            if each.pk == self.pk:
                rank = counter
                break
        return rank

    def gifts_sent(self):
        result = Customer.objects.filter(category=self).aggregate(total_gifts_sent=Sum('gifts_sent'))
        return result['total_gifts_sent'] or 0

    def surveys_sent(self):
        result = Customer.objects.filter(category=self).aggregate(total_suveys_sent=Sum('surveys_sent'))
        return result['total_suveys_sent'] or 0


    def last_activity(self):
        try:
            sale = Sale.objects.filter(customer__category=self).order_by('-transaction_date')[0]
            return sale.transaction_date
        except IndexError:
            return None


class Product(models.Model):
    """
    represents a product
    """
    IMPORTANCE_CHOICES = (
        (0, 'High'),
        (1, 'Medium'),
        (2, 'Low'),
        )
    name = models.CharField(_('name'), max_length=50, blank=False, null=False)
    date_released = models.DateField(_('date released'), blank=True, null=True)
    current_price = models.DecimalField(_('current price'), max_digits=10, decimal_places=2, blank=True, null=False,
        default=0)
    importance = models.SmallIntegerField(_('importance'), choices=IMPORTANCE_CHOICES, default=2)
    main_appeal = models.CharField(_('main appeal'), max_length=200, blank=True, null=False)
    surveys_sent = models.PositiveIntegerField(_('surveys sent'), default=0)

    # foreign key mappings goes here
    user = models.ForeignKey(User, blank=False, null=False)

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

    def get_rank(self):
        """
        gets rank of this product among other products
        basing on purchases. highest purchases leads to highest rank
        """
        products = Product.objects.filter(user=self.user).annotate(bought=Count('sale')).order_by('-bought')
        rank = len(products)
        counter = 0
        for product in products:
            counter = counter + 1
            if product.pk == self.pk:
                rank = counter
                break
        return rank

    def most_bought_category(self):
        """
        gets the category name that bought most.
        if multiple categories applicable, returns a concatenated string
        """
        categories = Category.objects.filter(customer__sale__product=self).annotate(
            bought=Count('customer__sale__product')).order_by('-bought')
        if categories:
            return groups[0].name
        return ''

    def most_common_path(self):
        return ''

    def total_sales(self):
        return Sale.objects.filter(product=self).count()

    def total_turnover_generated(self):
        """
        calculates total turnover generated by this customer
        """
        result = Sale.objects.filter(product=self).aggregate(turnover=Sum('price'))
        return result['turnover'] or 0.0

    def turnover_generated_in_month(self, month):
        result = Sale.objects.filter(product=self, transaction_date__month=str(month)).aggregate(turnover=Sum('price'))
        return result['turnover'] or 0.0


class Customer(models.Model):
    """
    represents a customer entity.
    """

    CONNECTION_CHOICES = (
        (0, 'High'),
        (1, 'Medium'),
        (2, 'Low'),
        )

    #first_name = models.CharField(_('first name'), max_length=50, blank=False, null=False)
    #last_name =  models.CharField(_('last name'), max_length=50, blank=False, null=False)
    full_name = models.CharField(_('full name'), max_length=50, blank=False, null=False, default="")

    company_name = models.CharField(_('company name'), max_length=100, blank=True, null=False, default="")
    email = models.EmailField(_('email'), max_length=75, blank=True, null=True)
    phone = models.CharField(_('phone'), max_length=15, blank=True, null=True)
    street = models.CharField(_('street'), max_length=100, blank=True, null=True)
    city = models.CharField(_('city'), max_length=100, blank=True, null=True)
    state = models.CharField(_('state'), max_length=75, blank=True, null=False)
    country = models.CharField(_('country'), max_length=75, blank=True, null=False)
    zipcode = models.CharField(_('zip'), max_length=10, blank=True, null=True)

    interests = models.CharField(_('core interests'), max_length=200, blank=True, null=False)
    connection = models.SmallIntegerField(_('connection'), choices=CONNECTION_CHOICES, default=2)
    gifts_sent = models.PositiveIntegerField(_('gifts sent'), default=0)
    surveys_sent = models.PositiveIntegerField(_('surveys sent'), default=0)

    user = models.ForeignKey(User, blank=False, null=False)
    #category = models.ForeignKey(Category, blank=False, null=False)

    class Meta:
        #ordering = ['first_name', 'last_name']
        ordering = ['full_name']

    #def full_name(self):
    #    return '%s %s'% (self.first_name, self.last_name)

    def first_name(self):
        return self.full_name.split(' ')[0]

    def last_name(self):
        return self.full_name.split(' ')[len(self.full_name.split(' ')) - 1]

    def __unicode__(self):
        #return self.full_name()
        return self.full_name

    def group(self):
        """
        calculates customer's virtual group
        """
        sale_count = self.sale_set.count()
        group = Group(self.user)
        if not sale_count:
            return group.GROUP_DEFINITIONS[0]
        elif sale_count == 1:
            return group.GROUP_DEFINITIONS[1]
        else:
            return group.GROUP_DEFINITIONS[2]

    def path(self):
        """
        path represents list of products sold in order of date
        """
        sales = Sale.objects.filter(customer=self)
        return ' > '.join(sale.product.name for sale in sales)

    def total_turnover_generated(self):
        """
        calculates total turnover generated by this customer
        """
        turnover = Sale.objects.filter(customer=self).aggregate(turnover=Sum('price'))
        return turnover['turnover'] or 0.0

    def total_purchases(self):
        """
        gets the total number of sales made by this customer
        """
        return Sale.objects.filter(customer=self).count()


class Campaign(models.Model):
    """
    represents a campaign, i.e. a marketing source
    """
    campaign_name = models.CharField(_('campaign name'), max_length=50, blank=False, null=False)
    start_date = models.DateField(_('date'), blank=True, null=True)

groups/models.py
# Create your models here.

core/forms.py
from django import forms
from core.models import Customer, Category, Product, Sale, Campaign

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        exclude = ['user']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = ['user']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['user']


class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id', None)
        super(SaleForm, self).__init__(*args, **kwargs)
        self.fields['product'].queryset = Product.objects.filter(user__id=user_id)
        self.fields['customer'].queryset = Customer.objects.filter(user__id=user_id)
        self.fields['marketing_source'].queryset = Campaign.objects.filter(user__id=user_id)


class CampaignForm(forms.ModelForm):
    class Meta:
        model = Campaign
        exclude = ['user']

groups/views.py
# Create your views here.
from django.shortcuts import  render_to_response
# ...
def detail(request):
    return render_to_response('groups/groups.html')

templates/core/base.html
{% extends "base.html" %}

templates/core/campaign.html
{% extends "core/base.html" %}

{% block scripts %}
    <script type="text/javascript" charset="utf-8">
        $('#tabCampaigns').addClass('selected');
    </script>
{% endblock %}

{% block content %}
    <form action='/home/search/' method='POST'>{% csrf_token %}
        <input class='content-searchbar' type=text name='word'/>
        <input style='vertical-align: middle; visibility: hidden; display: none;' type=submit value="Search"></input>
    </form>
    <h2 class='pad20'>Campaign List</h2>

    <table width=100% class='datatable'>

        <tr class='datarow pager'>
            <td colspan=4 style='text-align:right;'>
                Sort by &nbsp;
                <select name="sort" id="sort" style='width:150px; height:30px;'>
                    <option value="name" {% ifequal sort 'cname' %}selected="selected"{% endifequal %}
                    ">Campaign Name</option>
                    <option value="date" {% ifequal sort 'date' %}selected="selected"{% endifequal %}
                    ">Start Date</option>
                </select>&nbsp;&nbsp;

                {% if campaigns.has_previous %}
                    <a href="?page={{ campaigns.previous_page_number }}">previous</a>&nbsp;
                {% endif %}
                Page {{ campaigns.number }} of {{ campaigns.paginator.num_pages }}.&nbsp;
                {% if campaigns.has_next %}
                    <a href="?page={{ campaigns.next_page_number }}">next</a>
                {% endif %}
            </td>
        </tr>


        {% for campaign in campaigns.object_list %}
            <tr class='datarow'>
                <td class='icon-cell'><img src='/static/img/campaign.png'></td>
                <td class='datarow-prime'>
                    <a class='datarow-title'
                       href='/core/campaign/view/{{campaign.pk}}/'>{{ campaign.campaign_name }}</a>
                    <br>
                    <a class='datarow-action-link' href='/core/campaign/edit/{{campaign.pk}}/'><img
                            src='/static/img/edit.jpg'> Edit</a><span>&nbsp;&nbsp;</span>
                    <a class='datarow-action-link' href='/core/campaign/delete/{{campaign.pk}}/'
                       onclick='return getConfirmed("Campaign#{{campaign.pk}}");'><img src='/static/img/delete.png'>
                        Delete</a>
                </td>
                <td class='datarow-lables'>
                    <span class='datarow-item-lable'>Start Date</span>
                </td>
                <td class='datarow-items'>
                    <span class='datarow-item-value'>{{ campaign.start_date }}</span>
                </td>
            </tr>
        {% endfor %}

    </table>

    <script>

        $(document).ready(function () {
            // register a listener with JQ to intimate when sort order changed
            $("#sort").change(function (a) {
                // findout selected sort order
                // and navigate to ... with details
                window.location.href = '/core/campaign/?sort=' + $(this).val();
            });
        });

    </script>

{% endblock %}

templates/core/campaign_view.html
{% extends "core/base.html" %}

{% block scripts %}
    <script type="text/javascript" charset="utf-8">
        $('#tabCampaigns').addClass('selected');
    </script>
{% endblock %}

{% block content %}
    <h2>Campaign View</h2>

    <table class='viewtable' width=100%>
        <tr>
            <td class='icon-cell'><img src='/static/img/campaign.png'></td>
            <td colspan=4 class='viewrow-title'>{{ campaign.campaign_name }}
                <a class='viewrow-action-link' href='/core/campaign/edit/{{campaign.pk}}/'><img
                        src='/static/img/edit.jpg'> Edit</a><span>&nbsp;&nbsp;</span>
                <a class='datarow-action-link' href='/core/campaign/delete/{{campaign.pk}}/'
                   onclick='return getConfirmed("Campaign#{{campaign.pk}}");'><img src='/static/img/delete.png'> Delete</a>
            </td>
        </tr>

        <tr>

            <td></td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'>Campaign</span></td>
            <td class='viewrow-item-value'><span class='viewrow-item-value'><a
                    href='/core/campaign/view/{{campaign.pk}}/'>{{ campaign.campaign_name }}</a></span></td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'>Start Date</span></td>
            <td class='viewrow-item-value'><span class='viewrow-item-value'>{{ campaign.start_date }}</span></td>

        </tr>


    </table>

{% endblock %}

templates/core/customer_view.html
{% extends "core/base.html" %}

{% block scripts %}
    <script type="text/javascript" charset="utf-8">
        $('#tabCustomers').addClass('selected');
    </script>
{% endblock %}

{% block content %}
    <h2>Customer View</h2>

    <table class='viewtable' width=100%>
        <tr>
            <td class='icon-cell'><img src='/static/img/person.png'></td>
            <td colspan=4 class='viewrow-title'>{{ customer.full_name }}
                <br>
                <span style="font-style: italic; color: black; font-size: 12px;">{{ customer.company_name }}</span>

                <a class='viewrow-action-link' href='/core/customer/edit/{{customer.pk}}/'><img
                        src='/static/img/edit.jpg'> Edit</a><span>&nbsp;&nbsp;</span>
                <a class='datarow-action-link' href='/core/customer/delete/{{customer.pk}}/'
                   onclick='return getConfirmed("{{customer.full_name}}");'><img src='/static/img/delete.png'>
                    Delete</a>
            </td>
        </tr>
        <tr>

            <td></td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'>Total Turnover Generated</span></td>
            <td class='viewrow-item-value'><span
                    class='viewrow-item-value'>{{ customer.total_turnover_generated }}</span></td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'># of Purchases</span></td>
            <td class='viewrow-item-value'><span class='viewrow-item-value'>{{ customer.total_purchases }}</span></td>

        </tr>
        <tr>

            <td></td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'>Group</span></td>
            <td class='viewrow-item-value'><span class='viewrow-item-value'><a
                    href='/core/group/view/{{customer.group.id}}/'>{{ customer.group.name }}</a></span></td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'>Gifts Sent</span></td>
            <td class='viewrow-item-value'><span class='viewrow-item-value'>{{ customer.gifts_sent }}</span></td>

        </tr>
        <tr>

            <td></td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'>Core Interests</span></td>
            <td class='viewrow-item-value'><span class='viewrow-item-value'>{{ customer.interests }}</span></td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'>Surveys Sent</span></td>
            <td class='viewrow-item-value'><span class='viewrow-item-value'>{{ customer.surveys_sent }}</span></td>

        </tr>
        <tr>

            <td></td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'>Connection With You</span></td>
            <td class='viewrow-item-value'><span class='viewrow-item-value'>{{ customer.get_connection_display }}</span>
            </td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'>Path</span></td>
            <td class='viewrow-item-value'><span class='viewrow-item-value'>{{ customer.path }}</span></td>

        </tr>

        <tr>

            <td colspan=5 style="background-color:#e2eaed;"></td>

        </tr>

        <tr>

            <td></td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'>Street</span></td>
            <td class='viewrow-item-value'><span class='viewrow-item-value'>{{ customer.street }}</span></td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'>City</span></td>
            <td class='viewrow-item-value'><span class='viewrow-item-value'>{{ customer.city }}</span></td>

        </tr>

        <tr>

            <td></td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'>State</span></td>
            <td class='viewrow-item-value'><span class='viewrow-item-value'>{{ customer.state }}</span></td>
            <td class='viewrow-lables'><span class='viewrow-item-lable'>Country</span></td>
            <td class='viewrow-item-value'><span class='viewrow-item-value'>{{ customer.country }}</span></td>

        </tr>

    </table>

    <div>
{% endblock %}

templates/core/group.html
{% extends "core/base.html" %}

{% block scripts %}
    <script type="text/javascript" charset="utf-8">
        $('#tabGroups').addClass('selected');
    </script>
{% endblock %}

{% block content %}
    <form action='/home/search/' method='POST'>{% csrf_token %}
        <input class='content-searchbar' type=text name='word'/>
        <input style='vertical-align: middle; visibility: hidden; display: none;' type=submit value="Search"></input>
    </form>
    <h2 class='pad20'>Groups</h2>

    <table width=100% class='datatable'>

        {% for group in groups %}
            <tr class='datarow'>
                <td class='icon-cell'><img src='/static/img/group.png'></td>
                <td class='datarow-prime'><a class='datarow-title'
                                             href='/core/group/view/{{group.id}}/'>{{ group.name }}</a></td>
            </tr>
        {% endfor %}

    </table>

{% endblock %}

templates/core/group_view.html
{% extends "core/base.html" %}

{% block scripts %}
    <script type="text/javascript" charset="utf-8">
        $('#tabVategories').addClass('selected');
    </script>
{% endblock %}

{% block content %}
    <h2>Group View</h2>

    <table class='viewtable' width=100%>
        <tr>
            <td class='icon-cell'><img src='/static/img/group.png'></td>
            <td colspan=4 class='viewrow-title'>{{ group.name }}</td>
        </tr>
    </table>

    <h2 class='pad20'>Customers in {{ group.name }} group</h2>
    <table class='datatable' width=100%>
        <tr class='datarow pager'>
            <td colspan=4 style='text-align:right;'>
                {% if customers.has_previous %}
                    <a href="?page={{ customers.previous_page_number }}">previous</a>&nbsp;
                {% endif %}
                Page {{ customers.number }} of {{ customers.paginator.num_pages }}.&nbsp;
                {% if customers.has_next %}
                    <a href="?page={{ customers.next_page_number }}">next</a>
                {% endif %}
            </td>
        </tr>
        {% for customer in customers.object_list %}
            <tr class='datarow'>
                <td class='icon-cell'><img src='/static/img/person.png'></td>
                <td class='datarow-prime'>
                    <a class='datarow-title' href='/core/customer/view/{{customer.pk}}/'>{{ customer.full_name }}</a>
                </td>
                <td class='datarow-lables'>
                    <span class='datarow-item-lable'>Total revenue generated</span><br>
                    <span class='datarow-item-lable'></span>
                </td>
                <td class='datarow-items'>
			<span class='datarow-item-value'>{{ customer.total_turnover_generated }}<br>
			<span class='datarow-item-value'></span>
                </td>
            </tr>
        {% endfor %}
    </table>


{% endblock %}

templates/core/manage_campaign.html
{% extends "core/base.html" %}

{% block scripts %}
    <script type="text/javascript" charset="utf-8">
        $('#tabCampaigns').addClass('selected');
    </script>
{% endblock %}


{% block content %}
    <h2>{% if is_new %}Add a new{% else %}Edit{% endif %} Campaign</h2>

    {% if is_new %}
        <div class='csv-import-add'>
        </div>
    {% endif %}


    {% if form.errors %}
        <div class='error-panel'>
            <span style='font-weight: bold;'><img height=24px align=absmiddle width=24px src='/static/img/error.png'> Oops..errors occured!</span><br><br>
            {% for field in form %}
                {% if field.errors %}
                    <span>{{ field.label }}: {{ field.errors.0 }}</span><br>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}


    <form action="" method="post">{% csrf_token %}
        <table class='dataform' width=100%>
            <tr>
                <td><span class='dataform-lable'>{{ form.campaign_name.label }}</span><br>{{ form.campaign_name }}</td>
                <td><span class='dataform-lable'>{{ form.start_date.label }}</span><br>{{ form.start_date }}</td>
            </tr>


            <tr>
                <td colspan=2 style='text-align: right;'>
                    <input class='form-button-primary' type="submit" value="Save"/>
                    <input class='form-button-secondary' type=button value="Cancel"
                           onclick="JavaScript: window.location.href='/core/campaign/'"/>
                </td>
            </tr>
        </table>
    </form>


    <script>


        $(document).ready(function () {
            $("#id_start_date").datepicker();
            // register a listener with JQ to intimate when Product selection change
        });

    </script>


{% endblock %}

templates/core/manage_product.html
{% extends "core/base.html" %}

{% block scripts %}
    <script type="text/javascript" charset="utf-8">
        $('#tabProducts').addClass('selected');
    </script>
{% endblock %}


{% block content %}
    <h2>{% if is_new %}Add a new{% else %}Edit{% endif %} Product</h2>

    {% if is_new %}
        <div class='csv-import-add'>
            <p>
                Or <a href="/core/csv/product/">import</a> your data from a csv file
            </p>
        </div>
    {% endif %}

    {% if form.errors %}
        <div class='error-panel'>
            <span style='font-weight: bold;'><img height=24px align=absmiddle width=24px src='/static/img/error.png'> Oops..errors occured!</span><br><br>
            {% for field in form %}
                {% if field.errors %}
                    <span>{{ field.label }}: {{ field.errors.0 }}</span><br>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}


    <form action="" method="post">{% csrf_token %}
        <table class='dataform' width=100%>
            <tr>
                <td><span class='dataform-lable'>{{ form.name.label }}</span><br>{{ form.name }}</td>
                <td><span class='dataform-lable'>{{ form.current_price.label }}</span><br>{{ form.current_price }}</td>
            </tr>

            <tr>
                <td><span class='dataform-lable'>{{ form.main_appeal.label }}</span><br>{{ form.main_appeal }}</td>
                <td><span class='dataform-lable'>{{ form.date_released.label }}</span><br>{{ form.date_released }}</td>
            </tr>

            <tr>
                <td><span class='dataform-lable'>{{ form.importance.label }}</span><br>{{ form.importance }}</td>
                <td><span class='dataform-lable'>{{ form.surveys_sent.label }}</span><br>{{ form.surveys_sent }}</td>
            </tr>

            <tr>
                <td colspan=2 style='text-align: right;'>
                    <input class='form-button-primary' type="submit" value="Save"/>
                    <input class='form-button-secondary' type=button value="Cancel"
                           onclick="JavaScript: window.location.href='/core/product/'"/>
                </td>
            </tr>
        </table>
    </form>

    <script>
        $(function () {
            $("#id_date_released").datepicker();
        });
    </script>
{% endblock %}